### PR TITLE
deps: update regex to 1.0.

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
This failed due to the builder that tests Rust 1.12 ... not sure what you'll want to do here?

**Comment by waywardmonkeys** [comment]
Any thoughts on this?

**Comment by BurntSushi** [comment]
Thanks! I will put out a new minor release as a way to communicate that the minimum Rust version has been bumped.

**Comment by BurntSushi** [comment]
This is on crates.io in `tabwriter 1.1.0`.

**Pull request merged**
