### PR TITLE
deps: Update tabwriter-bin deps.

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
Any chance this could go in?

**Comment by BurntSushi** [comment]
@waywardmonkeys Can you update `docopt` to `1.0`?

Would you mind saying what you're using `tabwriter-bin` for?

**Comment by waywardmonkeys** [comment]
I'm actually not using it. I was just doing custodial stuff before and knocking down a bunch of things that used old versions of `lazy_static` and so on. And sure, I'll hit the docopt update.

**Comment by waywardmonkeys** [comment]
Updated!

**Comment by BurntSushi** [comment]
Great, thanks!

**Comment by BurntSushi** [comment]
This PR is in `tabwriter-bin 0.1.1` on crates.io.

**Comment by BurntSushi** [comment]
@pickfire If memory serves, this crate was actually written before Rust 1.0 was released. I'm not sure if you were using Rust in 2014, but back then, there was some serious amount of churn and not all the APIs we have today existed. So, there's a lot of holdover from those days I imagine.

I think for now I'd prefer not to update code just for cosmetic reasons. Instead, perhaps once Rust 2018 is out for a few cycles, we can just migrate to that in one step.

**Comment by pickfire** [comment]
@BurntSushi Wouldn't it be better for those developers which were using a recent version of rust to see the latest documentation for simpler and more concise code? (I think at least like 1.15 support which most do should be better than showing the code before rust 1.0 were release)

If they were to check, I personally think it might be better to show the recent example given that the old examples are still checked in into git history.

**Comment by BurntSushi** [comment]
@pickfire I don't know which code you're referring to. If it's in the public API docs, then yes, it should be updated. But it wasn't at all clear to me that you were referring to that vs just some random code in the crate. :-)

**Pull request merged**
