### PR TITLE
Use regex 0.2 when ansi_formatting is enabled

### PR DESCRIPTION
**Pull request by maximih**

### CODE REVIEW

**Comment by BurntSushi** [comment]
@maximih Thanks! Could you rebase this on to current master? It looks like you've got an extraneous commit. This is otherwise good to go!

**Comment by maximih** [comment]
Sorry for that. Should be ok now.

**Comment by BurntSushi** [comment]
Great thank you!

**Comment by BurntSushi** [comment]
`1.0.3` is on crates.io with this patch. Thanks again!

**Pull request merged**
